# Final, stable render.yaml for a Flask and external MySQL app

services:
  - type: web
    name: saas-project-manager # This must match your current service name
    env: python
    # Lock in a stable Python version to prevent compatibility issues
    pythonVersion: "3.11"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    # This section tells Render to use the environment variables
    # you have already set up in the dashboard.
    envVars:
      - key: MYSQL_HOST
        fromEnvVar: MYSQL_HOST
      - key: MYSQL_USER
        fromEnvVar: MYSQL_USER
      - key: MYSQL_PASSWORD
        fromEnvVar: MYSQL_PASSWORD
      - key: MYSQL_DB
        fromEnvVar: MYSQL_DB
      - key: MYSQL_PORT
        fromEnvVar: MYSQL_PORT
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
