# render.yaml for the web service only, explicitly using the free plan

services:
  - type: web
    name: saas-project-manager
    env: python
    plan: free # Explicitly setting the web service to the free tier
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MYSQL_HOST
        fromDatabase:
          name: saas-mysql-db # This must exactly match the name you gave your DB
          property: host
      - key: MYSQL_USER
        fromDatabase:
          name: saas-mysql-db
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: saas-mysql-db
          property: password
      - key: MYSQL_DB
        fromDatabase:
          name: saas-mysql-db
          property: database
