# A clean and simple render.yaml for a Flask and MySQL app

services:
  # This is the web service for your Python application
  - type: web
    name: saas-project-manager
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MYSQL_HOST
        fromDatabase:
          name: saas-mysql-db
          property: host
      - key: MYSQL_USER
        fromDatabase:
          name: saas-mysql-db
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: saas-mysql-db
          property: password
      - key: MYSQL_DB
        fromDatabase:
          name: saas-mysql-db
          property: database

  # This is the managed MySQL database service
  - type: db
    name: saas-mysql-db
    engine: mysql
    plan: free
